# Generated by Django 6.0.1 on 2026-01-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testassignment",
            name="score",
        ),
        migrations.AddField(
            model_name="testassignment",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="testassignment",
            name="obtained_marks",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
