# Generated by Django 6.0.1 on 2026-01-22 10:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_alter_chapter_options_alter_course_options_and_more"),
        ("tests", "0002_remove_testassignment_score_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answeroption",
            options={
                "verbose_name": "Answer Option",
                "verbose_name_plural": "Answer Options",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "Question", "verbose_name_plural": "Questions"},
        ),
        migrations.AlterModelOptions(
            name="studentanswer",
            options={
                "verbose_name": "Student Answer",
                "verbose_name_plural": "Student Answers",
            },
        ),
        migrations.AlterModelOptions(
            name="test",
            options={"verbose_name": "Test", "verbose_name_plural": "Tests"},
        ),
        migrations.AlterModelOptions(
            name="testassignment",
            options={
                "verbose_name": "Test Assignment",
                "verbose_name_plural": "Test Assignments",
            },
        ),
        migrations.AlterUniqueTogether(
            name="testassignment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="answeroption",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="studentanswer",
            name="evaluated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentanswer",
            name="question_marks",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="test",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="testassignment",
            name="attempt_number",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="testassignment",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="testassignment",
            name="due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testassignment",
            name="evaluated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testassignment",
            name="test_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="testassignment",
            name="total_marks",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testassignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="answeroption",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="options",
                to="tests.question",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questions",
                to="tests.test",
            ),
        ),
        migrations.AlterField(
            model_name="studentanswer",
            name="answered_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="studentanswer",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="tests.testassignment",
            ),
        ),
        migrations.AlterField(
            model_name="studentanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_answers",
                to="tests.question",
            ),
        ),
        migrations.AlterField(
            model_name="studentanswer",
            name="selected_option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="selected_by_students",
                to="tests.answeroption",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tests",
                to="courses.chapter",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tests",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="testassignment",
            name="assigned_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="testassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigned"),
                    ("started", "Started"),
                    ("submitted", "Submitted"),
                    ("evaluated", "Evaluated"),
                    ("cancelled", "Cancelled"),
                ],
                default="assigned",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="testassignment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="test_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="testassignment",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="tests.test",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="testassignment",
            unique_together={("student", "test", "attempt_number")},
        ),
        migrations.AddIndex(
            model_name="studentanswer",
            index=models.Index(
                fields=["assignment", "is_correct"],
                name="tests_stude_assignm_84eae9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentanswer",
            index=models.Index(
                fields=["question", "is_correct"], name="tests_stude_questio_f97b47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentanswer",
            index=models.Index(
                fields=["answered_at"], name="tests_stude_answere_f4e916_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="test",
            index=models.Index(
                fields=["course", "is_active"], name="tests_test_course__7c00aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="test",
            index=models.Index(
                fields=["is_active"], name="tests_test_is_acti_e3f3df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testassignment",
            index=models.Index(
                fields=["student", "status"], name="tests_testa_student_a6e2a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testassignment",
            index=models.Index(
                fields=["test", "status"], name="tests_testa_test_id_dfa58d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testassignment",
            index=models.Index(
                fields=["assigned_at"], name="tests_testa_assigne_1bfde5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testassignment",
            index=models.Index(
                fields=["student", "test"], name="tests_testa_student_4054a7_idx"
            ),
        ),
    ]
