# Generated by Django 6.0.1 on 2026-01-23 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_course_thumbnail"),
        ("tests", "0003_alter_answeroption_options_alter_question_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="studentanswer",
            name="tests_stude_assignm_84eae9_idx",
        ),
        migrations.RemoveIndex(
            model_name="studentanswer",
            name="tests_stude_questio_f97b47_idx",
        ),
        migrations.RemoveIndex(
            model_name="studentanswer",
            name="tests_stude_answere_f4e916_idx",
        ),
        migrations.RemoveIndex(
            model_name="test",
            name="tests_test_is_acti_e3f3df_idx",
        ),
        migrations.RemoveIndex(
            model_name="testassignment",
            name="tests_testa_student_4054a7_idx",
        ),
        migrations.AddField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="test",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="test",
            name="duration_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="is_published",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="answeroption",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="tests.question",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="tests.test",
            ),
        ),
        migrations.AlterField(
            model_name="testassignment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name="studentanswer",
            index=models.Index(
                fields=["assignment"], name="tests_stude_assignm_8e72aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentanswer",
            index=models.Index(
                fields=["question"], name="tests_stude_questio_574cab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="test",
            index=models.Index(
                fields=["is_published"], name="tests_test_is_publ_9388ca_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="answeroption",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_correct", True)),
                fields=("question",),
                name="one_correct_option_per_question",
            ),
        ),
        migrations.RemoveField(
            model_name="testassignment",
            name="is_completed",
        ),
    ]
