# Generated by Django 6.0.1 on 2026-01-26 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0004_remove_studentanswer_tests_stude_assignm_84eae9_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="duration_minutes",
        ),
    ]
