# Generated by Django 6.0.1 on 2026-01-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0005_remove_test_duration_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                blank=True, help_text="Duration in minutes for timed tests", null=True
            ),
        ),
    ]
