# Generated by Django 6.0.1 on 2026-01-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("stu_id", models.UUIDField()),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("STUDENT", "student")],
                        default="STUDENT",
                        max_length=20,
                    ),
                ),
                ("is_profile_completed", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "phone_number",
                    models.IntegerField(blank=True, max_length=11, null=True),
                ),
                ("age", models.IntegerField(blank=True, max_length=2, null=True)),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
