# Generated by Django 6.0.1 on 2026-01-23 06:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_options_user_phone_verified_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS accounts_user_groups;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS accounts_user_user_permissions;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
