# Generated by Django 6.0.1 on 2026-01-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_groups_user_is_staff_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="father_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
