# Generated by Django 6.0.1 on 2026-01-23 06:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_fix_user_groups_table"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE accounts_user_groups (
                id SERIAL NOT NULL PRIMARY KEY,
                user_id UUID NOT NULL REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED,
                group_id INTEGER NOT NULL REFERENCES auth_group(id) DEFERRABLE INITIALLY DEFERRED,
                UNIQUE (user_id, group_id)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS accounts_user_groups;",
        ),
        migrations.RunSQL(
            """
            CREATE TABLE accounts_user_user_permissions (
                id SERIAL NOT NULL PRIMARY KEY,
                user_id UUID NOT NULL REFERENCES accounts_user(id) DEFERRABLE INITIALLY DEFERRED,
                permission_id INTEGER NOT NULL REFERENCES auth_permission(id) DEFERRABLE INITIALLY DEFERRED,
                UNIQUE (user_id, permission_id)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS accounts_user_user_permissions;",
        ),
    ]
