# Generated by Django 6.0.1 on 2026-01-26 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_add_profile_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
    ]
