# Generated by Django 6.0.1 on 2026-01-22 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "enrollments",
            "0002_alter_enrollment_options_alter_enrollment_course_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="enrollment",
            name="enrollments_student_885f1d_idx",
        ),
        migrations.RemoveIndex(
            model_name="enrollment",
            name="enrollments_course__f8877c_idx",
        ),
        migrations.DeleteModel(
            name="Enrollment",
        ),
    ]
