# Generated by Django 6.0.1 on 2026-01-22 10:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
