# Generated by Django 6.0.1 on 2026-01-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_alter_course_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
