# Generated by Django 6.0.1 on 2026-01-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_course_update_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
