# Generated by Django 6.0.1 on 2026-01-22 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_chapter_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={
                "ordering": ["order"],
                "verbose_name": "Chapter",
                "verbose_name_plural": "Chapters",
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Course", "verbose_name_plural": "Courses"},
        ),
        migrations.RemoveField(
            model_name="course",
            name="update_at",
        ),
        migrations.AddField(
            model_name="course",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="chapters",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="title",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["is_active", "created_at"],
                name="courses_cou_is_acti_d8682d_idx",
            ),
        ),
    ]
