# Generated by Django 6.0.1 on 2026-01-22 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_alter_chapter_options_alter_course_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                help_text="Students enrolled in this course",
                related_name="enrolled_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
