# Generated by Django 6.0.1 on 2026-01-22 12:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_course_students"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoLecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "youtube_url",
                    models.URLField(
                        help_text="YouTube video URL or embed URL (e.g., https://www.youtube.com/watch?v=dQw4w9WgXcQ)"
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True, help_text="Video duration in seconds", null=True
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        help_text="Chapter this video belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="courses.chapter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Lecture",
                "verbose_name_plural": "Video Lectures",
                "ordering": ["chapter", "order"],
            },
        ),
        migrations.CreateModel(
            name="StudentNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        help_text="Chapter this note is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_notes",
                        to="courses.chapter",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student who created this note",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific video this note is for (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_notes",
                        to="courses.videolecture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Note",
                "verbose_name_plural": "Student Notes",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "note_type",
                    models.CharField(
                        choices=[("text", "Text Note"), ("file", "File Upload")],
                        default="text",
                        max_length=10,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Text content of the note", null=True
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="PDF, Word, or other document files",
                        null=True,
                        upload_to="admin_notes/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "txt",
                                    "xlsx",
                                    "pptx",
                                ]
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        help_text="Chapter this note belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_notes",
                        to="courses.chapter",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Admin who created this note",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_admin_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Note",
                "verbose_name_plural": "Admin Notes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["chapter"], name="courses_adm_chapter_5e3235_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="courses_adm_created_15e0d1_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="videolecture",
            index=models.Index(
                fields=["chapter", "order"], name="courses_vid_chapter_5ad64a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videolecture",
            index=models.Index(
                fields=["is_published"], name="courses_vid_is_publ_f19cb8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="videolecture",
            unique_together={("chapter", "order")},
        ),
        migrations.AddIndex(
            model_name="studentnote",
            index=models.Index(
                fields=["student", "chapter"], name="courses_stu_student_8f26a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentnote",
            index=models.Index(
                fields=["student", "video"], name="courses_stu_student_39838a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentnote",
            index=models.Index(
                fields=["updated_at"], name="courses_stu_updated_d032e1_idx"
            ),
        ),
    ]
