# Generated by Django 6.0.1 on 2026-01-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_videolecture_studentnote_adminnote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="course_thumbnails/"
            ),
        ),
    ]
