# Generated by Django 6.0.1 on 2026-01-26 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_course_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videolecture",
            name="duration_seconds",
        ),
    ]
